### ISSUE TITLE
Video File input

### ISSUE THREAD

**Issue by vijnasu** [chupakabra1996/RTSPServer#3]
I was just trying video source for resource: ".....*.h264"
mplayer/vlc/live555client doesn't play this back. 
mplayer gives Server type is 'unknown'.
Any idea, how to stream the video file?

**Comment by ramsafin** [comment]
Sorry for the late reply!
The code in this repo is intended for camera-based streaming only. 
That's why you may need to make some code modifications, e.g. change the framed source type (Live555) and input device parameters for FFmpeg. You can fork this repo and share the changes you made so it's possible to review them and, hopefully, find the source of issues.

Feel free to ask more questions regarding your issue.
